config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  devise_for :users # , ActiveAdmin::Devise.config
  mount RootApi => '/'
  mount Resque::Server.new, at: '/resque'
  post :toggle, to: 'locales#toggle'
  ActiveAdmin.routes(self)
  resources :events do
    resources :items
  end

  get 'events/page/(:page(.:format))', to: 'events#index'

  get 'about', to: 'about#index', as: 'about_index'
  scope '/:locale' do
    get 'about', to: 'about#index'
  end

  root 'events#index'
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  content     :text
#  finished_at :datetime
#  name        :string
#  state       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_events_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Event < ApplicationRecord
  include AASM

  belongs_to :user, counter_cache: true
  has_many :items, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :nullify
  has_many :commentators, through: :comments, source: :user
  has_many_attached :files, strict_loading: true

  validates :name, presence: true

  enum state: {
    created: 0,
    running: 10,
    pending: 20,
    finished: 30
  }

  aasm column: 'state' do
    state :created, initial: true, display: I18n.t('state.created')
    state :running, display: I18n.t('state.running')
    state :pending, display: I18n.t('state.pending')
    state :finished, display: I18n.t('state.finished')

    event :start do
      transitions from: %i[created running pending], to: :running
    end

    event :pend do
      transitions from: %i[running pending created], to: :pending
    end

    event :complete do
      transitions from: %i[running finished], to: :finished
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /events or /events.json
  def index
    Rack::MiniProfiler.step 'Загрузка событий' do
      @events = policy_scope(Event)
                  .includes(:items)
                  .page(params[:page])

    end
  end

  # GET /events/1 or /events/1.json
  def show
    authorize @event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params.merge(user: current_user))

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    authorize @event
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    authorize @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.with_attached_files.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :content, :done, :finished_at, :user, files: [])
  end
end

app/views/events/_event.html.slim
tr
  td.text-center = event.items.size
  td = link_to event.name, event, class: 'link-secondary'
  td.text-end = link_to edit_event_path(event), class: 'btn btn-danger' do
    span.fa.fa-pencil

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, 'error')} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'

  .field
    = f.label :content, class: 'form-label'
    = f.text_area :content, class: 'form-control'

  .field
    = f.label :files, class: 'form-label'
    = f.file_field :files, multiple: true, class: 'form-control'

  .field
    = f.label :finished_at, class: 'form-label'
    = f.datetime_field :finished_at, class: 'form-control'

  .field
    = f.label :done, class: 'form-check-label'
    = f.check_box :done, class: 'form-check-input'

  .actions = f.submit class: 'btn btn-secondary'

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

=> link_to 'Show', @event
=< link_to 'Back', events_path

app/views/events/index.html.slim
h1= t('activerecord.models.event')

table.table.table-striped
  thead
    tr
      th.text-center ID
      th Дело
      th

  tbody
    = render partial: 'event', collection: @events

p 
  = link_to t(:new_event), new_event_path
p
  = link_to t(:about), about_index_path
p
  = paginate @events

app/views/events/new.html.slim
h1 New event

== render 'form'

br

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice

p
  strong= t('activerecord.attributes.event.name')
  =< @event.name

p
  strong= t('activerecord.attributes.event.content')
  =< @event.content

p
  strong= t('activerecord.attributes.event.done')
  =< @event.done

p
  strong= t('activerecord.attributes.event.items')
  table
    - @event.items.order(created_at: :desc).each_with_index do |item, i|
      tr
        td = i + 1
        td = item.name

- if @event.files.attached?
  p
    strong= t('activerecord.attributes.event.files')
    table
      - @event.files.each_with_index do |file, i|
        tr
          td = i + 1
          td = link_to file.blob.filename, rails_blob_path(file, disposition: 'attachment'))

=> link_to t('label.edit'), edit_event_path(@event)
'|
=< link_to t('label.back'), events_path