config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  devise_for :users # , ActiveAdmin::Devise.config
  mount RootApi => '/'
  mount Resque::Server.new, at: '/resque'
  post :toggle, to: 'locales#toggle'
  ActiveAdmin.routes(self)
  resources :events do
    resources :items
  end

  get 'events/page/(:page(.:format))', to: 'events#index'

  get 'about', to: 'about#index', as: 'about_index'
  scope '/:locale' do
    get 'about', to: 'about#index'
  end

  root 'events#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Rolable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable

  before_destroy :log_before_destroy
  after_destroy :log_after_destroy
  before_validation :normalize_name, on: :create
  before_validation :set_role, on: %i[create update]
  before_validation :normalize_email, if: proc { |u| u.email }

  validates :email, :name, presence: true
  validates :email, :name, uniqueness: true
  validates :name, length: { maximum: 16, minimum: 2 }

  scope :default, -> { where(role_id: Role.find_by(code: :default).id) }
  scope :fresh, ->(created_at) { where('created_at > ?', created_at) }
  scope :default_fresh, ->(created_at) { default.fresh(created_at) }

  belongs_to :role
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_events,
           through: :comments,
           source: :commentable,
           source_type: :Event
  has_many :commented_users,
           through: :comments,
           source: :commentable,
           source_type: :User

  has_one_attached :avatar

  act_as_rolable

  before_save :ensure_authentication_token

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

  def attributes
    { name: name, email: email }
  end

  def description
    "#{name} (#{email})"
  end

  def active_for_authentication?
    super && active?
  end

  def normalize_email
    self.email = email.downcase
  end

  def set_role
    self.role ||= Role.find_by(code: :default)
  end

  def normalize_name
    self.name = name&.downcase&.titleize
  end

  def log_before_destroy
    Rails.logger.info '#######################################'
    Rails.logger.info "Собираемся удалить пользователя #{name}"
    Rails.logger.info '#######################################'
  end

  def log_after_destroy
    Rails.logger.info '#######################################'
    Rails.logger.info "Пользователь #{name} удален"
    Rails.logger.info '#######################################'
  end
end

app/views/admin/users/_form.html.slim
= form_for [:admin, @admin_user] do |f|
  - if @admin_user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_user.errors.count, 'error')} prohibited this admin_user from being saved:"
      ul
        - @admin_user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :email
    = f.text_field :email

  - if @admin_user.id != current_user.id
    .field
      = f.label :role
      = f.collection_select :role_id, Role.order(:name), :id, :name

  - if action_name == 'new'
    .field
      = f.label :password
      = f.password_field :password

    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation

  .actions = f.submit

app/views/admin/users/index.html.slim
h1 = action_title(User, action_name)

table cellspacing=0
  thead
    tr
      th
      th
      th
      th
      th
      th
      th
      th

  tbody
    - @admin_users.each do |user|
      tr style="background-color: #{ cycle('#ddd', '#fff') };"
        td = user.name
        td = user.email
        td = user.role.name
        td
          => user.events.count
          = t('activerecord.models.event', count: user.events.count)
        td
          => user.items.count
          = t('activerecord.models.item', count: user.items.count)
        td = link_to 'Show', admin_user_path(user)
        td = link_to 'Edit', edit_admin_user_path(user)
        td = link_to 'Destroy', admin_user_path(user), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_admin_user_path